version: '2'
services:
  corrdb:
    image: palingwende/native_corrdb
    container_name: corrdb
    ports:
     - "27019:27017"
    expose:
     - "27019"
    volumes:
     - /Users/fyc/CoRR-Test/data:/data
  corrapi:
    image: palingwende/native_corrapi
    ports:
     - "5100:5100"
    volumes:
     - /path/to/corr-storage:/home/corradmin/corr-storage
     - /path/to/corr-configs/api:/home/corradmin/corr/corr-api/config
    depends_on:
     - "corrdb"
    links:
     - "corrdb"
  corrcloud:
    image: palingwende/native_corrcloud
    ports:
     - "5200:5200"
    volumes:
     - /path/to/corr-storage:/home/corradmin/corr-storage
     - /path/to/corr-configs/cloud:/home/corradmin/corr/corr-cloud/config
     - /path/to/tmp:/tmp
    expose:
     - "5200"
    depends_on:
     - "corrdb"
    links:
     - "corrdb"
  corrview:
    image: palingwende/native_corrview
    ports:
     - "5000:5000"
    volumes:
      - /path/to/corr-configs/view:/home/corradmin/corr/corr-view/frontend/js/config
    depends_on:
     - "corrcloud"
